#!/usr/bin/env python3

import rospy
from geometry_msgs.msg import Twist
from std_msgs.msg import Bool
from std_msgs.msg import String
from visualization_msgs.msg import Marker


def marker():
    pub = rospy.Publisher('fmarker', Marker, queue_size=5)

    rospy.init_node('marker_dummy', anonymous=True)
    rate = rospy.Rate(50)
    marker = Marker()

    rospy.loginfo("marker dummy starts")
    while not rospy.is_shutdown():
        #process
        
        #publish marker	    
        marker.header.stamp = rospy.Time.now()
        marker.header.frame_id = "world"
        marker.ns = "One"
        marker.id = 1
        marker.type = 1
        marker.action = 0
        marker.pose.position.x = 1
        marker.pose.position.y = 1
        marker.pose.position.z = 1
        marker.pose.orientation.x = 0
        marker.pose.orientation.y = 0
        marker.pose.orientation.z = 0
        marker.pose.orientation.w = 1
        marker.scale.x = 1
        marker.scale.y = 1
        marker.scale.z = 1
        marker.color.r = 1
        marker.color.g = 0
        marker.color.b = 0
        marker.color.a = 1
        marker.lifetime = 0
        marker.frame_locked = True
        
        pub.publish(marker)
        rate.sleep()

if __name__ == '__main__':
    try:
        marker()
    except rospy.ROSInterruptException:
        pass
